import { VehicleComponent} from './vehicle.component';
import { RouterModule } from "@angular/router";

const routes = [
    {   path: '', component: VehicleComponent },
    { path: 'buildLevel', loadChildren: 'app/body/Admin/Vehicle/BuildLevels/buildLevel.module' },
    { path: 'equipment', loadChildren: 'app/body/Admin/Vehicle/Equipment/equipment.module' },
    { path: 'equipmenttype', loadChildren: 'app/body/Admin/Vehicle/EquipmentType/equipmenttype.module' },
    { path: 'titanRole', loadChildren: 'app/body/Admin/Vehicle/TitanRole/titanRole.module' },
    { path: 'platform', loadChildren: 'app/body/Admin/Vehicle/Platform/platform.module' },
    //{ path: 'titanUser', loadChildren: 'app/body/Admin/Vehicle/TitanUser/titanUser.module' },
    { path: 'market', loadChildren: 'app/body/Admin/Vehicle/Market/market.module' },
    { path: 'project', loadChildren: 'app/body/Admin/Vehicle/Project/project.module' },
    { path: 'tenant', loadChildren: 'app/body/Admin/Vehicle/Tenant/tenant.module' },
    { path: 'testfacility', loadChildren: 'app/body/Admin/Vehicle/TestFacility/testfacility.module' },
    { path: 'testVerificationMethod', loadChildren: 'app/body/Admin/Vehicle/TestVerificationMethod/testVerificationMethod.module' },
    { path: 'testStatus', loadChildren: 'app/body/Admin/Vehicle/TestStatus/testStatus.module' },
    //{ path: 'milestoneEvent', loadChildren: 'app/body/Admin/Vehicle/MilestoneEvent/milestoneEvent.module' },
    { path: 'milestoneStatus', loadChildren: 'app/body/Admin/Vehicle/MilestoneStatus/milestoneStatus.module' },
    { path: 'permission', loadChildren: 'app/body/Admin/Vehicle/Permission/permission.module' },
    { path: 'projectStatus', loadChildren: 'app/body/Admin/Vehicle/ProjectStatus/projectStatus.module' },
    { path: 'projectRole', loadChildren: 'app/body/Admin/Vehicle/ProjectRole/projectRole.module' },
    // { path: 'schedule', loadChildren: 'app/body/Admin/Vehicle/schedule/schedule.module' },
    { path: 'shift', loadChildren: 'app/body/Admin/Vehicle/Shift/shift.module' },
    { path: 'downTimeReason', loadChildren: 'app/body/Admin/Vehicle/DownTimeReason/downTimeReason.module' },
    // { path: 'entityField', loadChildren: 'app/body/Admin/Vehicle/EntityField/entityField.module' },
    // { path: 'contact', loadChildren: 'app/body/Admin/Vehicle/Contact/contact.module' },
    { path: 'accessGroup', loadChildren: 'app/body/Admin/Vehicle/AccessGroup/accessGroup.module' },
    { path: 'access', loadChildren: 'app/body/Admin/Vehicle/Access/access.module' },
    { path: 'role', loadChildren: 'app/body/Admin/Vehicle/Role/role.module' },
    { path: 'milestone', loadChildren: 'app/body/Admin/Vehicle/Milestone/milestone.module' },
    { path: 'milestoneCategory', loadChildren: 'app/body/Admin/Vehicle/MilestoneCategory/milestoneCategory.module' },
    { path: 'milestoneType', loadChildren: 'app/body/Admin/Vehicle/MilestoneType/milestoneType.module' },
    { path: 'grade', loadChildren: 'app/body/Admin/Vehicle/Grade/grade.module' },
    { path: 'modelName', loadChildren: 'app/body/Admin/Vehicle/ModelName/modelName.module' },
    { path: 'modelYear', loadChildren: 'app/body/Admin/Vehicle/ModelYear/modelYear.module' },
    { path: 'maintenanceFrequency', loadChildren: 'app/body/Admin/Vehicle/MaintenanceFrequency/maintenanceFrequency.module' },
    { path: 'vehicleType', loadChildren: 'app/body/Admin/Vehicle/VehicleType/vehicleType.module' },
    { path: 'requirementItemType', loadChildren: 'app/body/Admin/Vehicle/RequirementItemType/requirementItemType.module' },
    { path: 'sensorType', loadChildren: 'app/body/Admin/Vehicle/SensorType/sensorType.module' },
    { path: 'stepFrequency', loadChildren: 'app/body/Admin/Vehicle/StepFrequency/stepFrequency.module' },
    { path: 'stepType', loadChildren: 'app/body/Admin/Vehicle/StepType/stepType.module' },
    { path: 'testMode', loadChildren: 'app/body/Admin/Vehicle/TestMode/testMode.module' },
    { path: 'testType', loadChildren: 'app/body/Admin/Vehicle/TestType/testType.module' },
  ];

export default RouterModule.forChild(routes);
